
package ejercicio2;

import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Dani
 */
public class GUIs extends javax.swing.JFrame {

    /** Creates new form JFramEjercicio2 */
    public GUIs() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        bg = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        botonAlto = new javax.swing.JRadioButton();
        botonMediano = new javax.swing.JRadioButton();
        botonBajo = new javax.swing.JRadioButton();
        listaColores = new javax.swing.JComboBox();
        etiquetaColores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaNombres = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        botonLimpiar = new javax.swing.JButton();
        botonDialogo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        bg.add(botonAlto);
        bg.add(botonMediano);
        bg.add(botonBajo);

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo de botones de radio"));
        jPanel1.setToolTipText("Grupo de botones");

        botonAlto.setText("Alto");
        botonAlto.setToolTipText("");
        botonAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltoActionPerformed(evt);
            }
        });

        botonMediano.setText("Mediano");
        botonMediano.setToolTipText("");
        botonMediano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMedianoActionPerformed(evt);
            }
        });

        botonBajo.setText("Bajo");
        botonBajo.setToolTipText("");
        botonBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAlto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botonMediano)
                .addGap(38, 38, 38)
                .addComponent(botonBajo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAlto)
                    .addComponent(botonMediano)
                    .addComponent(botonBajo))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        listaColores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escriba o selecciones un color", "Rojo", "Amarillo", "Azul", "Verde", "Blanco" }));
        listaColores.setToolTipText("Lista de colores");
        listaColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaColoresActionPerformed(evt);
            }
        });

        etiquetaColores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiquetaColores.setText("Lista desplegable de colores:");
        etiquetaColores.setToolTipText("Etiqueta para lista de colores");

        listaNombres.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Juan Garcia", "Marta Montero", "Daniel Martin", "Adolfo Martin", "Lucia Carrasco" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaNombres.setToolTipText("Lista con nombres");
        listaNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listaNombresMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(listaNombres);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Lista de seleccion multiple");
        jLabel1.setToolTipText("Etiqueta de nombres");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Area de Texto"));

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        areaTexto.setToolTipText("Cuadro de Texto");
        jScrollPane2.setViewportView(areaTexto);

        botonLimpiar.setText("Limpiar");
        botonLimpiar.setToolTipText("Boton de limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonDialogo.setText("Dialogo");
        botonDialogo.setToolTipText("Boton de dialogo");
        botonDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDialogoActionPerformed(evt);
            }
        });

        jMenu3.setText("Look & Feel");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jMenu3.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaColores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(botonLimpiar)
                        .addGap(120, 120, 120)
                        .addComponent(botonDialogo)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaColores)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listaColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiar)
                    .addComponent(botonDialogo))
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void botonAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltoActionPerformed
        // TODO add your handling code here:
        areaTexto.append("Has seleccionado el boton de radio Alto\n");
    }//GEN-LAST:event_botonAltoActionPerformed

    private void botonMedianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMedianoActionPerformed
        // TODO add your handling code here:
        areaTexto.append("Has seleccionado el boton de radio Medio\n");
    }//GEN-LAST:event_botonMedianoActionPerformed

    private void botonBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajoActionPerformed
        // TODO add your handling code here:
        areaTexto.append("Has seleccionado el boton de radio Bajo\n");
    }//GEN-LAST:event_botonBajoActionPerformed

    private void listaColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaColoresActionPerformed
        // TODO add your handling code here:
        if(listaColores.getSelectedIndex() == 0){
            areaTexto.append("No se ha seleccionado ningun color\n");
        } else {
            areaTexto.append("El elemento seleccionado de la lista desplegable es\n");
            areaTexto.append("\t indice: " + listaColores.getSelectedIndex() + ", color " + listaColores.getSelectedItem() + "\n");
        }
    }//GEN-LAST:event_listaColoresActionPerformed

    private void listaNombresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNombresMouseExited
        // TODO add your handling code here:
        List<String> items = listaNombres.getSelectedValuesList();
        if(items.size() == 0){
            areaTexto.append("No hay elementos seleccionados de la lista de seleccion multiple\n");
        } else {
            areaTexto.append("Los elementos seleccionados de la lista de seleccion multiple son:\n");
            for(int i=0;i!=items.size();i++){
                areaTexto.append("\t" + (String)items.get(i) + "\n");
            }
        }
    }//GEN-LAST:event_listaNombresMouseExited

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        areaTexto.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDialogoActionPerformed
        // TODO add your handling code here:
        String val = JOptionPane.showInputDialog(this, "Cuantos dedos ves?", "Caja de dialogo", JOptionPane.QUESTION_MESSAGE);
        if((val!=null) && (!val.equals(""))){
            areaTexto.append("Has introducido " + val + "en el cuadro de texto\n");
        } else {
           areaTexto.append("No has introducido ningun valor en el cuadro de dialogo\n"); 
        }
    }//GEN-LAST:event_botonDialogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIs.class.getName()).log(java.util.logging.Level.SEVERE,
                                                                                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIs.class.getName()).log(java.util.logging.Level.SEVERE,
                                                                                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIs.class.getName()).log(java.util.logging.Level.SEVERE,
                                                                                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIs.class.getName()).log(java.util.logging.Level.SEVERE,
                                                                                    null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JRadioButton botonAlto;
    private javax.swing.JRadioButton botonBajo;
    private javax.swing.JButton botonDialogo;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JRadioButton botonMediano;
    private javax.swing.JLabel etiquetaColores;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox listaColores;
    private javax.swing.JList listaNombres;
    // End of variables declaration//GEN-END:variables

}
