CREATE TABLE AYUDAS 
(
  AÑO NUMBER NOT NULL 
, TIPO_AYUDA VARCHAR2(20) NOT NULL 
, EXTENSION NUMBER NOT NULL 
, CANTIDAD NUMBER NOT NULL 
, PARCELA NUMBER NOT NULL 
, CONSTRAINT AYUDAS_PK PRIMARY KEY 
  (
    AÑO 
  , PARCELA 
  )
  ENABLE 
);

CREATE TABLE PARCELAS 
(
  COD_PARCELA NUMBER NOT NULL 
, EXTENSION NUMBER NOT NULL 
, "REGADIO?" VARCHAR2(1) NOT NULL 
, PROPIETARIO NUMBER NOT NULL 
, CONSTRAINT PARCELAS_PK PRIMARY KEY 
  (
    COD_PARCELA 
  )
  ENABLE 
);

CREATE TABLE POZOS 
(
  COD_POZO NUMBER NOT NULL 
, PROFUNDIDAD NUMBER NOT NULL 
, CAUDAL NUMBER NOT NULL 
, "REGADIO?" VARCHAR2(1) NOT NULL 
, PARCELA NUMBER NOT NULL 
, CONSTRAINT POZOS_PK PRIMARY KEY 
  (
    COD_POZO 
  )
  ENABLE 
);

CREATE TABLE PROPIETARIO 
(
  DNI NUMBER NOT NULL 
, NOMBRE VARCHAR2(20) NOT NULL 
, DIRECCION VARCHAR2(50) NOT NULL 
, POBLACION VARCHAR2(20) NOT NULL 
, PROVINCIA VARCHAR2(20) NOT NULL 
, CP NUMBER NOT NULL 
, TELEFONO VARCHAR2(9) NOT NULL 
, CONSTRAINT PROPIETARIO_PK PRIMARY KEY 
  (
    DNI 
  )
  ENABLE 
);

ALTER TABLE AYUDAS
ADD CONSTRAINT AYUDAS_PARCELAS_FK FOREIGN KEY
(
  PARCELA 
)
REFERENCES PARCELAS
(
  COD_PARCELA 
)
ENABLE;

ALTER TABLE PARCELAS
ADD CONSTRAINT PARCELAS_PROPIETARIO_FK FOREIGN KEY
(
  PROPIETARIO 
)
REFERENCES PROPIETARIO
(
  DNI 
)
ENABLE;

ALTER TABLE POZOS
ADD CONSTRAINT POZOS_PARCELAS_FK FOREIGN KEY
(
  PARCELA 
)
REFERENCES PARCELAS
(
  COD_PARCELA 
)
ENABLE;
