
package evaluacion2;

import java.util.Random;

import java.util.regex.Pattern;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Dani
 */
public class MiAplicacion extends javax.swing.JFrame {

    /** Creates new form MiAplicacion */
    public MiAplicacion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        bGenerar = new javax.swing.JButton();
        textoMinimo = new javax.swing.JTextField();
        textoMaximo = new javax.swing.JTextField();
        etiquetaMax = new javax.swing.JLabel();
        etiquetaMin = new javax.swing.JLabel();
        etiquetaGenerado = new javax.swing.JLabel();
        textoResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bGenerar.setText("Generar numero");
        bGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerarActionPerformed(evt);
            }
        });

        etiquetaMax.setText("Valor maximo");

        etiquetaMin.setText("Valor minimo:");

        etiquetaGenerado.setText("Numero generado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(bGenerar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(etiquetaMin)
                        .addGap(26, 26, 26)
                        .addComponent(textoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(etiquetaMax)
                        .addGap(29, 29, 29)
                        .addComponent(textoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(etiquetaGenerado)
                        .addGap(26, 26, 26)
                        .addComponent(textoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaMax)
                    .addComponent(etiquetaMin))
                .addGap(112, 112, 112)
                .addComponent(bGenerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaGenerado)
                    .addComponent(textoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );

        pack();
    }//GEN-END:initComponents

    private void bGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerarActionPerformed
        // TODO add your handling code here:
        String comprobarMin = textoMinimo.getText();
        String comprobarMax = textoMaximo.getText();

        if (comprobarTextField(comprobarMin) && comprobarTextField(comprobarMax)) {
            int min = Integer.parseInt(textoMinimo.getText());
            int max = Integer.parseInt(textoMaximo.getText());
            if (min < max) {
                String resultado = Integer.toString(enteroAleatorio(min, max));
                textoResultado.setText(resultado);
            } else {
                JOptionPane.showMessageDialog(null, "El valor minimo debe ser menor que el valor maximo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Deben ser datos numericos!");
        }
    }//GEN-LAST:event_bGenerarActionPerformed
    
    public static int enteroAleatorio(int min, int max) {
        Random aleatorio = new Random();
        int numeroAle = aleatorio.nextInt((max - min) + 1) + min;
        return numeroAle;
    }

    public static boolean comprobarTextField(String texto) {
        boolean esEntero = Pattern.matches("([+-]{0,1})?[\\d]*", texto);
        return esEntero;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                 ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                 ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                 ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                 ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGenerar;
    private javax.swing.JLabel etiquetaGenerado;
    private javax.swing.JLabel etiquetaMax;
    private javax.swing.JLabel etiquetaMin;
    private javax.swing.JTextField textoMaximo;
    private javax.swing.JTextField textoMinimo;
    private javax.swing.JTextField textoResultado;
    // End of variables declaration//GEN-END:variables

}
